# .github/workflows/release.yml
name: Release Imput Package
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          always-auth: true
          registry-url: https://registry.npmjs.org
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Setup Git
        run: |
          git config --local user.name "Leonardo Petrucci"
          git config --local user.email "leonardo@petruc.ci"

      - run: pnpm install --frozen-lockfile

      - name: Build
        run: |-
          pnpm build

      - run: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
